import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen flex justify-center flex-col items-center space-x-4">
        <h1 className="font-semibold text-xl flex">
          <span className="px-0.5">Hii, I&apos;m</span>
          <p className="text-lavender px-0.5">Violet</p>
        </h1>

        <p className="flex text-justify w-80 flex-col">
          <span>I am a trans girl 🏳️‍⚧️ who likes to code, write, play with math and physics, and to read.</span>
          <span>
            You can find me on&nbsp;
            <Link href="https://discord.com/users/720250668388057138">
              <span className="text-green hovanim hover:text-yellow">Discord&nbsp;</span>
            </Link>
            and&nbsp;
            <Link href="https://github.com/violet-crein">
              <span className="text-green hovanim hover:text-yellow">GitHub</span>
            </Link>
            .
          </span>
        </p>

        <nav className='flex justify-center space-x-4 mt-2 mono'>
          <Link
            href="/"
            className="font-mid px-3 py-2 text-mauve select-none">
              <div className="px-1 hover:text-pink navanim">home</div>
          </Link>
          <Link
            href="/posts"
            className="font-mid px-3 py-2 text-mauve select-none">
              <div className="px-1 hover:text-pink navanim">posts</div>
          </Link>
        </nav>
      </main>
    </>
  )
}